### ISSUE TITLE
Feature request: Epub files

### ISSUE THREAD

**Issue by IpeTek** [stelzch/zotero.koplugin#10]
Hi, 

Thanks for this great app! 

I prefer to manage all my documents - even ebooks - in Zotero. Therefore, I wish we could handle and read even epubs and not only pdfs via this plugin.

All the best!

**Comment by stelzch** [comment]
Hi, thanks for your feedback!
I added epub to the whitelist so ebooks should show up now.

This has one usability catch, however: if there are items that have attachments in both formats (for example because you want to archive a book as fixed-layout PDF + rescalable EPUB), then currently it is going to show up in the Zotero Browser twice, with no indication which item is which format.
Ideally we would detect such situations (where there are multi-format attachments), display a single item and let the user select the format they want to open each time (just for reference, closing with the proposed solution).
